### ISSUE TITLE
Index Out of Bound error Fixed

### ISSUE THREAD

**Issue by RustAlgo** [RustAlgo/920_Straddle#1]
# Index Out of Bound error Fixed
## Problem- Security ID name is being searched as 4 May 2023 instead of 4 May 2023.

- Solved using zfill(2)

**Comment by RustAlgo** [comment]
Solved using zfill(2)

**Comment by ccmoradia** [comment]
Suppose I am running it with crontab in linux. How to get the trading logs to either in a text file or in a telegram.
