### ISSUE TITLE
Telegram alerts or log file

### ISSUE THREAD

**Issue by ccmoradia** [RustAlgo/920_Straddle#2]
Suppose I am running it with crontab in linux. How to get the trading logs to either in a text file or in a telegram.

**Comment by RustAlgo** [comment]
This is For Beginners, Wont Work on Linux hosted on AWS. Can integrate with Telegram with their API. Else can redirect standard output to maybe a text file. can redirect/mirror outputs to TG as well , You Can do whatever you fancy
